version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: hazard-report-db
    environment:
      - POSTGRES_USER=hazard_user
      - POSTGRES_PASSWORD=hazard_password
      - POSTGRES_DB=hazard_report
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hazard-report-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hazard_user:hazard_password@db:5432/hazard_report
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: hazard-report-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 